### PR TITLE
Enhance Navbar with Hover Effects and Underline Animation for Improve #180

### PR DESCRIPTION
**Pull request by amanreddy77**
### Pull Request Description

**Issue:** Enhancement of Navbar Visuals (#180)

**Description:**
This pull request addresses the lack of hover effects and animations in the navbar, which has been noted to make it visually unappealing. The proposed changes include:

1. **Hover Effects for the Logo:**
   - Implemented engaging hover effects for the navbar logo to enhance its interactivity and visual appeal.

2. **Underline Animations for Navigation Items:**
   - Added underline animations to the navigation items to improve their aesthetic and user experience when hovered over.

3. **Stylish Enhancements for the "Start Coding" Button:**
   - Redesigned the "Start Coding" button with stylish enhancements to make it more attractive and prominent.

**Enhancement Aim:**
The aim of this enhancement is to create a more engaging and visually appealing navbar that contributes positively to the overall user experience.

**Changes Made:**
- Updated CSS styles for the navbar logo and navigation items.
- Added hover effects and animations for better user feedback.
- Enhanced the styling of the "Start Coding" button.

**Screenshot:**

https://github.com/user-attachments/assets/0fe56100-6087-4c14-b199-4ee95a74af2e

### CODE REVIEW

**Comment by amanreddy77** [comment]
hi @arjunatapadkar can you please merge my PR

**Comment by arjunatapadkar** [comment]
Video is not working

**Comment by amanreddy77** [comment]
Just a second

**Comment by amanreddy77** [comment]
> Video is not working
is it ok now ?

**Comment by arjunatapadkar** [comment]
should be .mp4

**Comment by amanreddy77** [comment]
> should be .mp4

yeah i have updated it to mp4 you may check now

**Review by arjunatapadkar — APPROVED** [review]

**Pull request merged**
