### PR TITLE
Added Same Footer for all the pages in the Website

### PR DESCRIPTION
**Pull request by coder-writes**
This PR introduces a reusable footer component that has been implemented across all pages of the website. The footer now maintains uniformity and consistency, ensuring a seamless user experience.

Key Changes:
1. Created a single footer component to be used across the entire website.
2. Ensured that the footer adapts to different background colours, making it visible on both light and dark modes.
3. Removed duplicate footer code from individual pages and replaced it with the new footer component for better maintainability.

Testing:

 1.The footer has been tested on multiple pages to ensure it appears and functions as expected on all pages.
 2. The footer remains responsive and adapts well to different screen sizes and devices.

Screenshot 2024-10-11 162135

Screenshot 2024-10-11 162151

<h2>Video</h2>

A video demonstrating the changes has been attached to showcase the consistent footer across all pages and its behavior on different backgrounds.

(https://drive.google.com/uc?id=1VPPZpMB0Um6hT8qpRu6IKhAgyUUJg-mt&export=download)

### CODE REVIEW

**Comment by coder-writes** [comment]
@arjunatapadkar Hey kindly review the PR and if there is any scope of improvement, please let me know

**Review by arjunatapadkar — CHANGES_REQUESTED** [review]
Add the same footer component to following pages also

pages/upcoming.jsx
pages/error page.jsx
pages/cheatsheet/cheatsheet.jsx
pages/interview/interviewprep.jsx
pages/interview/machine coding.jsx
pages/product/product.jsx

And will merge this immediately

**Comment by coder-writes** [comment]
okay completing within an hour

**Comment by coder-writes** [comment]
hey @arjunatapadkar i made the all the necessary changes
Changes to `Footer` component:

* [`src/components/core/Footer.jsx`](diffhunk://#diff-030d6be3fe3f38e284067f90f722741504b18684468a945591b30df011d94dc9L1-R88): Updated the footer structure to include new navigation links, community links, and social media icons.

Integration of `Footer` component:

* [`src/pages/ErrorPage.jsx`](diffhunk://#diff-1db987029d0c318ae80192bb45129c35f2f3f754655d70e329f00c3a320e2b31R2-R10): Added the new `Footer` component. [[1]](diffhunk://#diff-1db987029d0c318ae80192bb45129c35f2f3f754655d70e329f00c3a320e2b31R2-R10) [[2]](diffhunk://#diff-1db987029d0c318ae80192bb45129c35f2f3f754655d70e329f00c3a320e2b31R26-R31)
* [`src/pages/Homepage.jsx`](diffhunk://#diff-4245ca1b392ca012f273c916f2988e62589f6f05fd276304b0b1f56e73957bbfR18-R19): Replaced the old footer with the new `Footer` component. [[1]](diffhunk://#diff-4245ca1b392ca012f273c916f2988e62589f6f05fd276304b0b1f56e73957bbfR18-R19) [[2]](diffhunk://#diff-4245ca1b392ca012f273c916f2988e62589f6f05fd276304b0b1f56e73957bbfL392-R394)
* [`src/pages/cheatsheet/Cheatsheet.jsx`](diffhunk://#diff-08684aa9a13ab86411a788c93c06ebfc84d2a42767b48216187987a692a65974R5): Replaced the old footer with the new `Footer` component. [[1]](diffhunk://#diff-08684aa9a13ab86411a788c93c06ebfc84d2a42767b48216187987a692a65974R5) [[2]](diffhunk://#diff-08684aa9a13ab86411a788c93c06ebfc84d2a42767b48216187987a692a65974L72-R74)
* [`src/pages/interview/ChallengeDetail.jsx`](diffhunk://#diff-55045b8657eebfc1ef474c7dbe4cc581f631f85e267d083582b5d844cd788111L5-R5): Replaced `SpecialFooter` with the new `Footer` component. [[1]](diffhunk://#diff-55045b8657eebfc1ef474c7dbe4cc581f631f85e267d083582b5d844cd788111L5-R5) [[2]](diffhunk://#diff-55045b8657eebfc1ef474c7dbe4cc581f631f85e267d083582b5d844cd788111L102-R102)
* [`src/pages/interview/InterviewPrep.jsx`](diffhunk://#diff-ba2f0d369e5f423c400aa79a244f90b3a7cec0d81bf3be14b544e14081d4714aL107-R107): Updated to use the new `Footer` component.
* [`src/pages/interview/machineCoding.jsx`](diffhunk://#diff-0ccdfa8f10933c1278db9ab0cf0219f4a999c5d0af1508fba8a104abc7bb7e62L4-R4): Replaced `SpecialFooter` with the new `Footer` component. [[1]](diffhunk://#diff-0ccdfa8f10933c1278db9ab0cf0219f4a999c5d0af1508fba8a104abc7bb7e62L4-R4) [[2]](diffhunk://#diff-0ccdfa8f10933c1278db9ab0cf0219f4a999c5d0af1508fba8a104abc7bb7e62L99-R99)
* [`src/pages/playground/Playground.jsx`](diffhunk://#diff-5cd044604225a05753954e3e4956cc76f0e84b8444a96cdec69b054026c3059eR5): Replaced the old footer with the new `Footer` component. [[1]](diffhunk://#diff-5cd044604225a05753954e3e4956cc76f0e84b8444a96cdec69b054026c3059eR5) [[2]](diffhunk://#diff-5cd044604225a05753954e3e4956cc76f0e84b8444a96cdec69b054026c3059eL448-R450)
* [`src/pages/products/product.jsx`](diffhunk://#diff-75bb134a30967891bc1aa6a35cd8f207d45943676d3b0220dd4fc2c569f874f4L4-R4): Replaced `SpecialFooter` with the new `Footer` component. [[1]](diffhunk://#diff-75bb134a30967891bc1aa6a35cd8f207d45943676d3b0220dd4fc2c569f874f4L4-R4) [[2]](diffhunk://#diff-75bb134a30967891bc1aa6a35cd8f207d45943676d3b0220dd4fc2c569f874f4L107-R108)

**Comment by arjunatapadkar** [comment]
Resolve merge conflicts

**Comment by coder-writes** [comment]
> Resolve merge conflicts

Made Necessary Changes

**Pull request merged**
