### PR TITLE
Added DS Problem

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
Changes made: 

- Created a new page for the endpoint /dsproblem.
- Design a simple UI that matches the rest of the website theme. 
- Added a button on the homepage that redirects to the /dsproblem page. 

Screenshots:
image
image
image

Related issue:
#106

### CODE REVIEW

**Comment by arjunatapadkar** [comment]
Please read the issue carefully before raising PR

**Comment by J-B-Mugundh** [comment]
@arjunatapadkar Could u please tell me where i went wrong? I think I've added everything mentioned in the issue. A button in home that redirects to /dsproblem + Changes are done via apicontext only + the page for adding ds problems.

**Comment by arjunatapadkar** [comment]
ds problems button should not be at homepage 
you will get the card for DSA  - at interview preparation page  "codeteria.vercel.app/interview"

**Comment by J-B-Mugundh** [comment]
> ds problems button should not be at homepage you will get the card for DSA - at interview preparation page "codeteria.vercel.app/interview"

image

Yeah I have added there which u could find from the above image. However, it was mentioned to be added in home page too. Please check this. It was mentioned to add a button in home page at 3rd point. If it's not needed, I could remove that and make a commit. So, please let me know. 

image

**Comment by arjunatapadkar** [comment]
Ohh Sorry, I didn't noticed it. I just forgot to update the issue. Sorry for inconvenience but could you please remove it from homepage and will merge it.

**Comment by arjunatapadkar** [comment]
did you got the empty response from the API, actually it has some sample dataset

**Comment by J-B-Mugundh** [comment]
> Ohh Sorry, I didn't noticed it. I just forgot to update the issue. Sorry for inconvenience but could you please remove it from homepage and will merge it.

Sure!

**Comment by J-B-Mugundh** [comment]
> did you got the empty response from the API, actually it has some sample dataset

Could u tell where it is? Actually I worked on this around 4-5 days ago. I'm not sure if it was present during that time

**Comment by J-B-Mugundh** [comment]
@arjunatapadkar I've updated it and resolved the merge conflicts as well. Please check!

**Review by arjunatapadkar — APPROVED** [review]

**Pull request merged**
