### PR TITLE
fix: Making The Navbar sticky

### PR DESCRIPTION
**Pull request by BKarthik7**
Makes the Navbar sticky #8

### CODE REVIEW

**Comment by BKarthik7** [comment]
Sorry by mistake clicked to deploy

**Review by arjunatapadkar — COMMENTED** [review]
Can you just show the UI changes snapshots

**Comment by BKarthik7** [comment]
Before: https://github.com/user-attachments/assets/ffeefcff-16e5-4631-beb3-9a8724fe5d73
After: https://github.com/user-attachments/assets/4bc35de8-ebc5-49e5-b667-277cb2bc7ab8
Here is the Before and after video  of the change to navbar

**Comment by arjunatapadkar** [comment]
@BKarthik7 give me the tags you want to add to this issue

**Comment by BKarthik7** [comment]
@arjunatapadkar extra tag level1 will do the job

**Pull request merged**
