### PR TITLE
Added hovers and other transition effects to sections and cards (#27 issue resolved)

### PR DESCRIPTION
**Pull request by 770navyasharma**
#27 issue resolved

### CODE REVIEW

**Comment by arjunatapadkar** [comment]
@770navyasharma can you share demo visuals of updated ui

**Comment by 770navyasharma** [comment]
> @770navyasharma can you share demo visuals of updated ui

Yess

Screenshot 2024-10-03 at 11 15 21 PM
Screenshot 2024-10-03 at 11 15 31 PM
Screenshot 2024-10-03 at 11 15 40 PM

**Review by arjunatapadkar — APPROVED** [review]

**Comment by arjunatapadkar** [comment]
@770navyasharma creating new issue you may be interested in

**Comment by 770navyasharma** [comment]
@arjunatapadkar Please add labels to the PR

**Pull request merged**
