### PR TITLE
Added FAQ page

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@arjunatapadkar 
I have added FAQ page succesfully
kindly merge the Subscription letter PR first, otherwise it will raise Conflicts here

Kindly check it out

https://github.com/user-attachments/assets/16d76206-40ff-4a67-afed-3c83ebb3e228

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@arjunatapadkar 
Resolved the conflicts
Kindly check now

**Review by arjunatapadkar — CHANGES_REQUESTED** [review]
1.You changed import statement of /Terms to /terms
2. Change file name faqs.jsx to Faqs.jsx

**Comment by AswaniBolisetti** [comment]
@arjunatapadkar 
I have changed as you mentioned
Kindly check it out

**Review by arjunatapadkar — CHANGES_REQUESTED** [review]
Change filename - faqs.jsx to Faqs.jsx

**Comment by AswaniBolisetti** [comment]
@arjunatapadkar 
I have changed

**Comment by AswaniBolisetti** [comment]
@arjunatapadkar 
faqs

**Review by arjunatapadkar — APPROVED** [review]

**Pull request merged**
