### PR TITLE
Fixes #146 Data Leak Bug Fixed

### LINKED ISSUE #146: [BUG ] : Data Leakage in Console.
Whenever Cheatsheet is opened , all the data is being displayed in console window. 

image

@arjunatapadkar I can fix this bug and also, I want to work any other please assign me a issue.

### PR DESCRIPTION
**Pull request by Akshithsaai**
Fixes #146 

@arjunatapadkar I have changed the code to ensure no data leaks from cheats page, challenges , Api context page.

### CODE REVIEW

**Review by arjunatapadkar — CHANGES_REQUESTED** [review]
Remove  env file

**Comment by Akshithsaai** [comment]
Ok I will commit after removing right now.
@arjunatapadkar

**Comment by Akshithsaai** [comment]
@arjunatapadkar I have removed the .env file. Please check .

**Review by arjunatapadkar — APPROVED** [review]

**Comment by Akshithsaai** [comment]
@arjunatapadkar I would like to work on other issue . Please assign me any other issue you need help with .

**Comment by arjunatapadkar** [comment]
mention me inside the issuse you want to work on  @Akshithsaai

**Comment by Akshithsaai** [comment]
You can Assign me any issue that is not assigned yet @arjunatapadkar . I will work on it.

**Pull request merged**
