### PR TITLE
only enhanced UI compaltiblity of Cheatsheets for dark mode

### PR DESCRIPTION
**Pull request by abhishekpanthee**
before __
befo1
after--
after1

### CODE REVIEW

**Comment by arjunatapadkar** [comment]
Give me one snapshot for light theme @abhishekpanthee

**Comment by abhishekpanthee** [comment]
Screenshot from 2024-10-07 14-03-44
@arjunatapadkar

**Review by arjunatapadkar — COMMENTED** [review]
Screenshot_20241007_135358
Don't change this blue colour to purple

**Comment by abhishekpanthee** [comment]
Screenshot from 2024-10-07 14-21-40
yup fixed it  I am comitting right now 
@arjunatapadkar

**Comment by abhishekpanthee** [comment]
Screenshot from 2024-10-07 14-21-40
Screenshot from 2024-10-07 14-25-02
Screenshot from 2024-10-07 14-25-07

**Comment by abhishekpanthee** [comment]
wait i still nedd for dark mode
sorry to ping carelessly

**Comment by abhishekpanthee** [comment]
@arjunatapadkar  yup done it thanks for the guidance 
Screenshot from 2024-10-07 14-30-41
Screenshot from 2024-10-07 14-30-47

**Comment by arjunatapadkar** [comment]
You only changed bg
change texts,  and card border also @abhishekpanthee

**Comment by abhishekpanthee** [comment]
@arjunatapadkar   i did change text colors  i am really confused 
image
here you can see the comparison 
https://github.com/arjunatapadkar/codeteria/pull/80#issuecomment-2396300097

**Pull request closed without merging**
