### PR TITLE
Fix broken links in MainNavbar component

### PR DESCRIPTION
**Pull request by coder-writes**
Refactor the MainNavbar component to fix broken links. The "Community" and "Pro" tabs were previously pointing to the "/upcoming" page, but have been updated to point to the "/error" page. This ensures that the links in the MainNavbar component are correctly directing users to the intended pages.

Here is  the Video Demonstrating the changes 
https://drive.google.com/uc?id=1F0x0lK3y-Em_d7pH7umEuH2Rhjh2KR3K&export=download

Hey @arjunatapadkar , Please have a look into the changes.

### CODE REVIEW

**Comment by coder-writes** [comment]
hey @arjunatapadkar  Can You Please Have a look into the pull Request and tell me if you want any further improvements ?

**Comment by coder-writes** [comment]
@arjunatapadkar please merge this pull request when i have done your work that I mentioned in the issue #135

**Comment by arjunatapadkar** [comment]
It should redirect to upcoming page

**Comment by coder-writes** [comment]
@arjunatapadkar I can make the changes according to you

**Pull request closed without merging**
