### PR TITLE
added cursor animation #98

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@arjunatapadkar 
I have added the cursor following animation

https://github.com/user-attachments/assets/8fd349f4-b475-49ad-b026-62914f3c3e94

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@arjunatapadkar 
could you please tell me why it is showing like this
hack

**Review by arjunatapadkar — APPROVED** [review]

**Comment by AswaniBolisetti** [comment]
@arjunatapadkar could you please merge this, i took so much effort please, dont delete

**Comment by arjunatapadkar** [comment]
keep contributing @AswaniBolisetti

**Comment by AswaniBolisetti** [comment]
@arjunatapadkar Thank you so much

**Comment by arjunatapadkar** [comment]
You can check issue 107 @AswaniBolisetti

**Comment by AswaniBolisetti** [comment]
@arjunatapadkar Sure I'll raise an issue, and try to do it

**Pull request merged**
