### PR TITLE
Done the changes...

### PR DESCRIPTION
**Pull request by SaanyaGarg5**
i have redesigned the landing page... 
pls check and let me know....

### CODE REVIEW

**Comment by SaanyaGarg5** [comment]
I have redesigned the  interview page...

**Comment by arjunatapadkar** [comment]
Share the snapshots/video of ui

**Comment by SaanyaGarg5** [comment]
Screenshot (266)
Screenshot (267)
Screenshot (268)

**Comment by SaanyaGarg5** [comment]
Screenshot (270)
Screenshot (271)
Screenshot (272)
Screenshot (273)

**Comment by SaanyaGarg5** [comment]
these all are for landing page

**Comment by arjunatapadkar** [comment]
I mean snapshots of ui not of code

**Comment by SaanyaGarg5** [comment]
why have you closed it?

**Comment by SaanyaGarg5** [comment]
do i have to design the landing and interview page?

**Comment by arjunatapadkar** [comment]
Homepage of the project should be redesigned. And snapshots of ui should be uploaded for review with the PR

**Pull request closed without merging**
