### PR TITLE
solved #121 Created Quiz page

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
changes made :
1.Added Quiz button to access on homepage
2.On clicking button goes to quizes page
3.Added 3 Quizes in Quizes page

https://github.com/user-attachments/assets/263d47b7-9efb-4bef-ab1d-ae7b40c03c90

image
image

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Please merge this request sir.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir please merge this pull request

**Review by arjunatapadkar — CHANGES_REQUESTED** [review]
Redirect to upcoming page when clicked on quiz 1, 2, 3

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
redirected to upcoming on clickingg the quiz 1 ,2,3

https://github.com/user-attachments/assets/61d81215-9304-45cb-bcc1-b4530e59955c

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir please add level3 label ,and merge it sir by considering the work and efforts done by me

**Review by arjunatapadkar — APPROVED** [review]

**Pull request merged**
