### PR TITLE
Added Basic System Design Concepts data in MongoDB Schema format

### LINKED ISSUE #108: Add System Design Concepts
I would like to contribute on adding basic concepts of System design along with example (Either Code or Image). 

Main Concepts include:

- Network Protocols
- Load Balancing
- Memcaching
- Performance vs Scalability
- Latency vs Throughput
- Availability vs Consistency
- CAP Theorem, etc.

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
Description: This PR brings in the following System Design Concepts along with the MongoDB schema format suitable to be added in later. 

- Network Protocols
- Load Balancing
- Memcaching
- Performance vs Scalability
- Latency vs Throughput
- Availability vs Consistency
- CAP Theorem

Resolves: #108

### CODE REVIEW

**Comment by J-B-Mugundh** [comment]
@arjunatapadkar Please let me know if this works! I've added tags as for each topic well, which could be helpful while searching

**Review by arjunatapadkar — COMMENTED** [review]
yeah, its good go ahead

**Comment by J-B-Mugundh** [comment]
> yeah, its good go ahead

Should I create a page?

**Comment by arjunatapadkar** [comment]
Please create

**Comment by J-B-Mugundh** [comment]
> Please create

I thought it was just content creation for this issue as I'm providing a much insighted content along with the schema as well. Shall I create a new issue for creating page?

**Comment by arjunatapadkar** [comment]
Yeah you can

**Comment by J-B-Mugundh** [comment]
> Yeah you can

Okay sure! Please close this PR and assign labels if we're good with the content. I'll work on creating the page

**Comment by J-B-Mugundh** [comment]
@arjunatapadkar Hey bro.. may i please know why this was closed? The content creation task was done right? I couldn't contribute to the other issue since I had exams. Please reopen it and merge

**Comment by J-B-Mugundh** [comment]
@sanjay-kv @MastanSayyad Is there anything u could do for this? please look into this

**Comment by MastanSayyad** [comment]
Hi @arjunatapadkar Can you give context why you closed the PR?

**Comment by arjunatapadkar** [comment]
This repository is for frontend only and storing the content inside the files goes against the project structure. And since this issue got assigned a lot of other content related issues were created. that's why I am closing all the content related issues.

Sorry for inconvinience but this is not going to merge, you can contribute to other frontend issues.

**Comment by J-B-Mugundh** [comment]
> This repository is for frontend only and storing the content inside the files goes against the project structure. And since this issue got assigned a lot of other content related issues were created. that's why I am closing all the content related issues.
> 
> Sorry for inconvinience but this is not going to merge, you can contribute to other frontend issues.


Shouldn't this have been informed before I started working right? I  clearly asked the requirements and communicated as best as possible and you did reply. Then only I've started working. Please revisit the convo we had in the issue. 

@MastanSayyad

**Comment by J-B-Mugundh** [comment]
@MastanSayyad Could u please look on this?

**Comment by MastanSayyad** [comment]
@arjunatapadkar as I can see you have discussed with @J-B-Mugundh in this PR and even after discussing you closed the PR, so it was a waste of time for the Contributor, you can reopen this PR and merge it give proper labelling and revert it back 

So that he could have points for his efforts!

**Comment by J-B-Mugundh** [comment]
@arjunatapadkar Please add the necessary labels which we agreed while the issue was created. Thank you!

**Comment by J-B-Mugundh** [comment]
@arjunatapadkar bro, please add the necessary label as mentioned in the issue. It's been more than a day since the program manager informed you.

**Comment by MastanSayyad** [comment]
@arjunatapadkar Add me as a collaborator so that I can do these things by myself, as I'm reviewing the Contributors PRs, i may revisit your repo to reduce points of some contributors. 

Also add `level 2` for this PR

**Comment by MastanSayyad** [comment]
@arjunatapadkar Add me as a collaborator in your repo,I need to fix the labels for some contributors and also know that points for PRs will not reflect in leaderboard if there is ni `gssoc-ext` label

**Pull request merged**
